# Generated by Django 5.0.2 on 2024-02-20 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_drinkcategory_drinks_category_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrinkCategory',
            new_name='DrinksCategory',
        ),
    ]
