# Generated by Django 5.0.2 on 2024-03-09 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_employees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
