# Generated by Django 5.0.2 on 2024-03-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
