# Generated by Django 5.0.3 on 2024-03-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['price'], name='BooksAPI_bo_price_3901df_idx'),
        ),
    ]
