# Generated by Django 5.0.3 on 2024-03-21 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksAPI', '0005_alter_book_inventory'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='BooksAPI_bo_price_3901df_idx',
        ),
    ]
